"""Export router — PDF and Excel document exports."""

import logging
import os
import uuid
from typing import Literal

from fastapi import APIRouter, Depends, HTTPException, Query, Response, status
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.document import Document
from app.models.user import User
from app.services.auth_service import get_current_user
from app.services.export_service import (
    generate_excel,
    generate_pdf,
    sanitize_filename,
)

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/documents", tags=["Export"])


async def get_document_for_export(
    id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> Document:
    """Fetch document and verify ownership using the pooled async session."""
    query = select(Document).where(
        Document.id == id,
        Document.user_id == current_user.id,
    )
    result = await db.execute(query)
    document = result.scalar_one_or_none()
    if not document:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Document not found",
        )
    return document


@router.get("/{id}/export")
def export_document(
    id: uuid.UUID,
    format: Literal["pdf", "excel"] = Query(
        ...,
        description="Export format ('pdf' or 'excel')",
    ),
    document: Document = Depends(get_document_for_export),
    current_user: User = Depends(get_current_user),
):
    """Export document metadata, AI analysis, and raw text as PDF or Excel.

    Synchronous def route running in FastAPI worker thread pool for blocking
    ReportLab and openpyxl operations.
    """
    # 1. Build Content-Disposition filename safely
    safe_name = sanitize_filename(document.original_filename)
    base_stem, _ = os.path.splitext(safe_name)
    base_stem = base_stem.rstrip(". _") or "document"

    # 2. Call generator based on format
    if format == "pdf":
        file_bytes = generate_pdf(document)
        media_type = "application/pdf"
        download_filename = f"{base_stem}.pdf"
    elif format == "excel":
        file_bytes = generate_excel(document)
        media_type = (
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
        download_filename = f"{base_stem}.xlsx"
    else:
        # FastAPI's Literal validation guarantees format is 'pdf' or 'excel'
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=f"Unsupported format '{format}'",
        )

    # 3. Return standard Response with generated bytes
    headers = {
        "Content-Disposition": f'attachment; filename="{download_filename}"'
    }

    return Response(
        content=file_bytes,
        media_type=media_type,
        headers=headers,
    )
