"""add ai processing fields and document_chunks table

Revision ID: d0c4bb464884
Revises: 9dbfb3069000
Create Date: 2026-10-01 09:52:34.791714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'd0c4bb464884'
down_revision: Union[str, None] = '9dbfb3069000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('documents', sa.Column('document_type', sa.String(length=50), server_default=sa.text("'OTHER'"), nullable=False))
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False))
    op.add_column('documents', sa.Column('classification_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'classification_confidence')
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'summary')
    op.drop_column('documents', 'document_type')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
